### ISSUE TITLE
Add pytest for pull requests

### ISSUE THREAD

**Issue by asgerius** [peleiden/pelutils#10]
@sorenmulli Det plejer at være sådan noget nederen noget, du altid tager dig af.

**Comment by sorenmulli** [comment]
Skal nok ❤️

**Comment by asgerius** [comment]
Jeg har et specifikt ønske om coverage og vil specifikt frabede mig linting

**Comment by sorenmulli** [comment]
![billede](https://64.media.tumblr.com/9d8babbd0b0341db853418e74707275d/tumblr_nkm193YfdF1qiuc6yo1_500.gif)

Men skal nok

**Comment by asgerius** [comment]
Bruh, jeg er tilstrækkeligt venstreorienteret til at være tilstrækkeligt berettiget til alt.
