### ISSUE TITLE
Allow to document repeated parser calls in same location in a job resuming setting

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/pelutils#140]
Any big-brained reason that, currently, we force `prepare_directory` to both delete and write docfile?

I would find it nice to either have the docfile writing into a sub-function so I can call that or otherwise have a flag in the function so that I enable/disable deletion. (I sometimes work without deletion :P)

waddayafink?

**Comment by asgerius** [comment]
I think my reasoning with it was that you could have cases where you would then write a docfile that would not correspond to the content of the folder, but I see the usecase where you are resuming a job. Maybe a separate documentation method with append functionality would work?

**Comment by sorenmulli** [comment]
Tru dat, we want to be truthful bois.
I'll change this to be about appending documentation
