### ISSUE TITLE
Option to only run a subset of sections in config file

### ISSUE THREAD

**Issue by asgerius** [peleiden/pelutils#169]

**Comment by asgerius** [comment]
@sorenmulli Kunne det ikke være nice, hvis man fx havde
```
[A]
du=lugter

[B]
du=stinker

[C]
du=dejlig
```
og så kunne køre `python kør.pyton sted -c ovenstående.ini:A:B` for kun at køre de to første fx? Så behøver man heller ikke oprette en masse config-filer for at køre jobsne i flere processer.

**Comment by sorenmulli** [comment]
Based
