### ISSUE TITLE
Make it easy to deploy from GitHub

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/pelutils#17]
Awaits #10 .

There exists a lot of nice GH actions integrations with PyPi: 
See f.x.
- https://github.com/actions/starter-workflows/blob/c59b62dee0eae1f9f368b7011cf05c2fc42cf084/ci/python-publish.yml

**Comment by asgerius** [comment]
@sorenmulli Løs lige alle vores problemer med denne https://cibuildwheel.readthedocs.io/en/stable/

**Comment by asgerius** [comment]
I forlængelse af ovensstående: https://gertjanvandenburg.com/blog/wheels/

Ser ud til, at #12 kan løses med det
