### ISSUE TITLE
Maybe don't allow importing everything from top level?

### ISSUE THREAD

**Issue by asgerius** [peleiden/pelutils#57]
Might be nice to avoid looooong import statements. With 0.7.0 breaking everything, now would be a good time if done. It will also make imports more sensible IMO.

@sorenmulli

**Comment by sorenmulli** [comment]
Need to argue a bit - I think there are fine points to be made FOR `from pelutils import whatever you want`

**Comment by asgerius** [comment]
You should switch to Java
