### ISSUE TITLE
Add more log levels

### ISSUE THREAD

**Issue by asgerius** [peleiden/pelutils#6]
Implementation specifics will have to be considered.

- Should level usage be optional or a forced replacement to the current verbose/non-verbose system?
- How should it be logged? I would prefer a style like in most logs, s.t. lines are time stamp followed by level and then the actual log. This would also be fairly easy to implement. Then whether or not the level is logged would be controlled by the `with_timestamp` parameter (which maybe should be renamed to `with_info` or something similar).
- What levels should there be? And should it be possible to add custom levels? To keep it simple, I don't think custom levels need be supported, at least to begin with. It might be ideal to use similar levels as the built-in [`logging` module](https://docs.python.org/3/library/logging.html#levels):
```py
class Levels(IntEnum):
    SECTION = 6
    CRITICAL = 5
    ERROR = 4
    WARNING = 3
    INFO = 2
    DEBUG = 1
    VERBOSE = 0
```
- How should they be used? Obviously `._log` should have an argument giving the level, but should there be specific methods for each level maybe? This would make it impossible to have custom levels, but that is probably not an issue. However, this would require some quite verbose code, as several methods with the same prototype.
- If specific methods are not implemented (and maybe even if they are), the levels should be gettable without the extra import, I think. They could be defined as properties on `_Logger`.
- `_Unverbose` should be able to handle the levels

In any case, this looks like a major release with significant breaking changes.

Branch: feature/loglevel

@sorenmulli

**Comment by sorenmulli** [comment]
This would be super nice.

Personally, the most important thing is easy access to a `log_warn` or `log_debug
